// Progress and planning UI. All saved mutations go through the game's bridge.
const api=window.TycoonCareerBridge;
const copy={
 es:{route:'Ruta',title:'Tu siguiente paso',intro:'Aprende haciendo. Estos objetivos no exigen ganar una operación ni asumir más riesgo.',missions:['Explora el mercado','Revisa tu plan de efectivo','Realiza tu primera inversión','Abre tu primer negocio','Compra tu primera vivienda'],market:'Ir al mercado',biz:'Ver negocios',homes:'Ver viviendas',plan:'Plan de efectivo',help:'La reserva se fija en dinero, no en un porcentaje permanente. Limita nuevas compras personales de activos; no bloquea viviendas, negocios ni pérdidas. Puedes cambiarla cuando quieras.',free:'Disponible para invertir',reserve:'Reserva protegida',none:'Sin reserva',save:'Plan actualizado',tools:'Herramientas de tu vivienda',basic:'Estudio: plan de efectivo y ruta inicial.',forecast:'Despacho desbloqueado: ingresos pasivos proyectados en 7 días',projection:'Estimación del juego a ritmo actual; puede cambiar y no incluye gastos ni operaciones.',analysis:'Análisis desbloqueado: concentración de tu cartera',largest:'Mayor posición',locked:'El apartamento añade la proyección de ingresos. El ático añade el análisis de concentración.',next:'Siguiente vivienda',missing:'Te faltan',available:'Disponible en la tienda',chapter:'Necesitas avanzar de capítulo',complete:'Ruta inicial completada. Continúa con tu negocio y tu siguiente vivienda.',close:'Cerrar',purchase:'Compra realizada',risk:'No necesitas invertir todo tu efectivo. Decide primero cuánto quieres conservar.',empty:'Todavía no tienes posiciones.',done:'Completado'},
 en:{route:'Journey',title:'Your next step',intro:'Learn by doing. These goals never require winning a trade or taking more risk.',missions:['Explore the market','Review your cash plan','Make your first investment','Open your first business','Buy your first home'],market:'Open market',biz:'See businesses',homes:'See homes',plan:'Cash plan',help:'The reserve is a fixed cash amount, not a permanent percentage. It limits new personal asset purchases, not homes, businesses or losses. You can change it anytime.',free:'Available to invest',reserve:'Protected reserve',none:'No reserve',save:'Plan updated',tools:'Tools in your home',basic:'Studio: cash plan and starter journey.',forecast:'Office unlocked: projected passive income over 7 days',projection:'Game estimate at the current rate; may change and excludes expenses and trades.',analysis:'Analysis unlocked: portfolio concentration',largest:'Largest position',locked:'The apartment adds income projections. The loft adds concentration analysis.',next:'Next home',missing:'Still needed',available:'Available in the shop',chapter:'Advance to the required chapter',complete:'Starter journey complete. Continue with your business and next home.',close:'Close',purchase:'Purchase complete',risk:'You do not need to invest all your cash. Decide what to keep first.',empty:'You have no positions yet.',done:'Complete'},
 zh:{route:'路线',title:'下一步',intro:'边做边学。目标不要求交易盈利，也不要求承担更多风险。',missions:['探索市场','检查现金计划','完成首次投资','开办首个企业','购买首套住宅'],market:'进入市场',biz:'查看企业',homes:'查看住宅',plan:'现金计划',help:'储备是固定现金金额，不是永久比例。它限制个人账户的新资产购买，但不限制住宅、企业或亏损。可随时调整。',free:'可投资现金',reserve:'受保护的储备',none:'不设储备',save:'计划已更新',tools:'住宅工具',basic:'工作室：现金计划和入门路线。',forecast:'办公室已解锁：未来7天预计被动收入',projection:'按游戏当前收入估算，可能变化，不含支出和交易。',analysis:'分析已解锁：投资组合集中度',largest:'最大持仓',locked:'公寓解锁收入预测，阁楼解锁集中度分析。',next:'下一套住宅',missing:'尚需',available:'可在商店购买',chapter:'需要推进章节',complete:'入门路线完成。继续发展企业和升级住宅。',close:'关闭',purchase:'购买成功',risk:'不必投入所有现金。先决定保留多少。',empty:'尚无持仓。',done:'已完成'}
};
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const button=document.createElement('button');button.className='career-launch';button.dataset.roomUi='';button.type='button';
const dialog=document.createElement('dialog');dialog.className='career-dialog';dialog.dataset.roomUi='';dialog.setAttribute('aria-labelledby','career-title');
document.body.append(button,dialog);let previous='',lastFeedback=0;
function render(force=false){
 const s=api.snapshot(),c=copy[s.language]||copy.es;button.hidden=!s.playing;
 const complete=[s.visited,s.reviewed,s.traded>0,s.businesses>0,s.tier>0];
 button.textContent=c.route+' '+complete.filter(Boolean).length+'/5';
 const key=JSON.stringify(s);if(!force&&(!dialog.open||key===previous))return;previous=key;
 const total=s.holdings.reduce((sum,a)=>sum+a.value,0),largest=s.holdings.reduce((best,a)=>a.value>best.value?a:best,{value:0,name:''});
 dialog.innerHTML='<form method="dialog"><header><h2 id="career-title">'+c.title+'</h2><button aria-label="'+c.close+'">×</button></header></form><p>'+c.intro+'</p><ol class="career-missions">'+c.missions.map((m,i)=>'<li class="'+(complete[i]?'completed':'')+'">'+(complete[i]?'✓ ':i+1+'. ')+m+(complete[i]?'<span class="career-sr"> '+c.done+'</span>':'')+'</li>').join('')+'</ol><div class="career-actions"><button data-go="screenTrade">'+c.market+'</button><button data-go="screenBiz">'+c.biz+'</button><button data-go="screenShop">'+c.homes+'</button></div><section><h3>'+c.plan+'</h3><p>'+c.risk+'</p><div class="career-numbers"><div>'+c.reserve+'<strong>'+money(s.reserve)+'</strong></div><div>'+c.free+'<strong>'+money(Math.max(0,s.cash-s.reserve))+'</strong></div></div><div class="career-actions">'+[0,.1,.25,.5].map(p=>'<button data-reserve="'+p+'">'+(p?Math.round(p*100)+'%':c.none)+'</button>').join('')+'</div><p class="career-small">'+c.help+'</p></section><section><h3>'+c.tools+'</h3><p>'+c.basic+'</p>'+(s.tier>=1?'<p>'+c.forecast+'<strong class="career-value">'+money(s.income*7)+'</strong></p><p class="career-small">'+c.projection+'</p>':'')+(s.tier>=2?'<p>'+c.analysis+'</p><p>'+(total?c.largest+': '+esc(largest.name)+' — '+Math.round(largest.value/total*100)+'%':c.empty)+'</p>':'<p class="career-small">'+c.locked+'</p>')+'</section>'+(s.next?'<section><h3>'+c.next+'</h3><p>'+money(s.next.cost)+' · '+c.missing+' '+money(Math.max(0,s.next.cost-s.cash))+'</p><p class="career-small">'+(s.next.available?c.available:c.chapter)+'</p></section>':'')+(complete.every(Boolean)?'<p>'+c.complete+'</p>':'')+'<p class="career-feedback" role="status"></p>';
}
button.addEventListener('click',()=>{render(true);dialog.showModal();});
dialog.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.go){dialog.close();api.open(b.dataset.go);render();}if(b.dataset.reserve!==undefined){api.plan(Number(b.dataset.reserve));render(true);dialog.querySelector('.career-feedback').textContent=(copy[api.snapshot().language]||copy.es).save;}});
window.addEventListener('tycoon-purchase',()=>{if(Date.now()-lastFeedback<500)return;lastFeedback=Date.now();button.classList.remove('career-purchased');void button.offsetWidth;button.classList.add('career-purchased');});
// Do not rebuild an open form every time the simulated price changes.
setInterval(()=>{if(!dialog.open)render();},1200);render();
