// Entirely fictional game products. No external quotes or real investment advice.
const labels={es:{title:'Patrimonio y largo plazo',cash:'Efectivo',worth:'Patrimonio neto',note:'Viviendas y negocios se valoran al coste de compra; no son dinero disponible. Se resta la deuda bancaria.',names:['Fondo diversificado','Fondo de bonos','Plan de pensiones'],terms:'Productos ficticios. Su valor puede subir o bajar. Sin rentabilidad garantizada. El plan aplica un 5% de coste a cada aportación retirada antes de 30 días del juego. Los otros fondos permiten retirar sin penalización.',invest:'Aportar',withdraw:'Retirar todo',amount:'Importe',error:'Revisa el importe y el efectivo disponible (se respeta tu reserva).',done:'Operación realizada',goal:'Objetivo de largo plazo: mantener una aportación al plan durante 30 días del juego.',mature:'Aportaciones con plazo cumplido',bank:'Finanzas',close:'Cerrar',owned:'Valor actual'},en:{title:'Net worth and long term',cash:'Cash',worth:'Net worth',note:'Homes and businesses are valued at purchase cost, not available cash. Bank debt is deducted.',names:['Diversified fund','Bond fund','Pension plan'],terms:'Fictional products. Values can rise or fall. No guaranteed return. The plan charges 5% on each contribution withdrawn before 30 game days. Other funds can be withdrawn without penalty.',invest:'Contribute',withdraw:'Withdraw all',amount:'Amount',error:'Check the amount and available cash (your reserve is protected).',done:'Transaction complete',goal:'Long-term goal: keep a pension contribution for 30 game days.',mature:'Contributions past the holding period',bank:'Finance',close:'Close',owned:'Current value'},zh:{title:'净资产与长期计划',cash:'现金',worth:'净资产',note:'住宅与企业按购买成本计价，不是可用现金。银行债务已扣除。',names:['多元基金','债券基金','养老金计划'],terms:'虚构游戏产品。价值可升可跌，不保证收益。每笔养老金投入在30个游戏日内取出收取5%费用。其他基金可无罚金赎回。',invest:'投入',withdraw:'全部赎回',amount:'金额',error:'请检查金额及可用现金，保留的储备受保护。',done:'操作完成',goal:'长期目标：将一笔养老金保留30个游戏日。',mature:'已达到持有期限的投入',bank:'理财',close:'关闭',owned:'当前价值'}};
const ids=['fund','bonds','pension'];
function nav(id){const d=Math.max(0,Number(state.day)||0),vol=id==='bonds'?.006:id==='pension'?.025:.06;return 100*Math.exp(.0001*d+vol*Math.sin(d*.21));}
function lots(id){return (state.longTerm?.[id]||[]).filter(l=>Number.isFinite(l.units)&&l.units>0);}
window.TycoonFinance={
 value:()=>ids.reduce((s,id)=>s+lots(id).reduce((v,l)=>v+l.units*nav(id),0),0),
 durable:()=>{let v=0;SHOP_ITEMS.forEach(i=>{if(i.cat==='inmueble'&&i.id!=='home1b'&&state.shop?.owned?.[i.id])v+=i.cost;});BUSINESSES.forEach(b=>{for(let i=0;i<Math.min(b.max,state.bizOwned?.[b.id]||0);i++)v+=i===0?b.baseCost:Math.round(b.baseCost*Math.pow(b.upgF,i));});return v;},
 transact:(id,amount,withdraw=false)=>{
  if(!gameStarted||!ids.includes(id))return false;
  if(!withdraw&&(!Number.isFinite(amount)||amount<=0||amount>Math.max(0,state.cash-(state.career?.reserve||0))))return false;
  if(!state.longTerm)state.longTerm={};
  if(withdraw){state.cash+=lots(id).reduce((sum,l)=>sum+l.units*nav(id)*(id==='pension'&&state.day-l.day<30?.95:1),0);state.longTerm[id]=[];}
  else{state.cash-=amount;if(!Array.isArray(state.longTerm[id]))state.longTerm[id]=[];state.longTerm[id].push({units:amount/nav(id),day:state.day});}
  updateTopBar();saveGame(true);return true;
 }
};
const dialog=document.createElement('dialog');dialog.className='career-dialog';dialog.dataset.roomUi='';document.body.append(dialog);
function render(){const c=labels[state.language]||labels.es;dialog.innerHTML='<form method="dialog"><header><h2>'+c.title+'</h2><button aria-label="'+c.close+'">×</button></header></form><p>'+c.cash+': '+fmt(state.cash)+' · '+c.worth+': '+fmt(netWorth())+'</p><p class="career-small">'+c.note+'</p><p>'+c.terms+'</p>'+ids.map((id,i)=>'<section><h3>'+c.names[i]+'</h3><p>'+c.owned+': '+fmt(lots(id).reduce((s,l)=>s+l.units*nav(id),0))+'</p><label>'+c.amount+' <input type="number" min="1" step="1" inputmode="decimal" data-amount="'+id+'" style="width:100%;padding:10px;color:inherit;background:#182d35;border:1px solid #758a80;border-radius:8px"></label><div class="career-actions"><button data-buy="'+id+'">'+c.invest+'</button><button data-sell="'+id+'">'+c.withdraw+'</button></div></section>').join('')+'<p>'+c.goal+'</p><p>'+c.mature+': '+lots('pension').filter(l=>state.day-l.day>=30).length+'</p><p role="status"></p>';}
dialog.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const id=b.dataset.buy||b.dataset.sell;if(!id)return;const amount=Number(dialog.querySelector('[data-amount="'+id+'"]').value),ok=window.TycoonFinance.transact(id,amount,!!b.dataset.sell);if(ok)render();dialog.querySelector('[role="status"]').textContent=(labels[state.language]||labels.es)[ok?'done':'error'];});
window.openFinance=()=>{render();dialog.showModal();};
// Place the entry in the existing planning hub, not another floating button.
setInterval(()=>{const hub=document.querySelector('.career-dialog .career-actions');if(hub&&!hub.querySelector('[data-finance]')){const b=document.createElement('button');b.dataset.finance='';b.textContent=(labels[state.language]||labels.es).bank;b.onclick=()=>{hub.closest('dialog').close();window.openFinance();};hub.append(b);}},500);
updateTopBar();
